name: ArixBoxPvP
version: 1.0.0
main: com.arix.boxpvp.ArixBoxPvP
api-version: '1.20'
author: jackgeldi23

commands:
  kasaayarla:
    permission: op
  kasasil:
    permission: op
  anahtarver:
    permission: skript.anahtarver
  duyuru:
    permission: op
  bakimaal:
    permission: op
  ip:
    description: IP adresi
  yardim:
    description: Yardım menusu
  medya:
    description: Medya sartlari
  kurallar:
    description: Kurallar
  cekilis:
    permission: op
  pv:
    description: Sanal depo
  pv1:
    description: PV 1
  pv2:
    description: PV 2
  pv3:
    description: PV 3
  pv4:
    description: PV 4
  pv5:
    description: PV 5
  pvsil:
    permission: op
  pvbak:
    permission: op
    
